django-eccomerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('product.urls', namespace='products'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from . import views


app_name = 'product'

urlpatterns = [
    path('', views.productlist, name='product_list'),
    path('<slug:category_slug>', views.productlist, name='product_list_category'),
    path('detail/<slug:product_slug>', views.productdetail, name='product_detail'),
]

product/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import slugify


# Create your models here.
class Product(models.Model):
    CONDITION_TYPE = (
        ("new", "New"),
        ("used", "Used"),
    )
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    condition = models.CharField(max_length=100, choices=CONDITION_TYPE)
    price = models.IntegerField(default=0)
    created = models.DateTimeField(default=timezone.now)
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True)
    brand = models.ForeignKey('Brand', on_delete=models.SET_NULL, null=True)
    image = models.ImageField(upload_to="main_products", blank=True, null=True)

    slug = models.SlugField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug and self.name:
            self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class ProductImages(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    product_image = models.ImageField(upload_to="product_images", blank=True, null=True)

    class Meta:
        verbose_name = 'Product Image'
        verbose_name_plural = 'Product Images'

    def __str__(self):
        return self.product.name


class Category(models.Model):
    category_name = models.CharField(max_length=50)
    image_icon = models.ImageField(upload_to="category_images", blank=True, null=True)

    slug = models.SlugField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug and self.category_name:
            self.slug = slugify(self.category_name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.category_name


class Brand(models.Model):
    brand_name = models.CharField(max_length=50)

    def __str__(self):
        return self.brand_name

product/views.py
from django.shortcuts import render
from .models import Product, ProductImages, Category
from django.core.paginator import Paginator
from django.db.models import Count, Q



def productlist(request, category_slug=None):
    category = None
    all_products = Product.objects.all().order_by('id')
    categorylist = Category.objects.annotate(total_count=Count('product'))

    if category_slug:
        category = Category.objects.get(slug=category_slug)
        all_products = all_products.filter(category=category)

    search_query = request.GET.get('q')
    if search_query:
        all_products = all_products.filter(
            Q(name__icontains=search_query) |
            Q(description__icontains=search_query) |
            Q(condition__icontains=search_query) |
            Q(brand__brand_name__icontains=search_query) |
            Q(category__category_name__icontains=search_query)
        )

    paginator = Paginator(all_products, 5)
    page = request.GET.get('page')
    all_products = paginator.get_page(page)
    template = 'Product/product_list.html'
    context = {'product_list': all_products, 'category_list': categorylist, 'category': category}

    return render(request, template, context)


def productdetail(request, product_slug):
    print(product_slug)
    detail = Product.objects.get(slug=product_slug)
    images = ProductImages.objects.filter(product=detail)
    template = 'Product/product_detail.html'
    context = {'product_detail': detail, 'product_images': images}
    return render(request, template, context)

product/templates/Product/product_detail.html
{% extends 'base.html' %}

{% load static %}

{% block body %}

	<!--single-page-->
	<div class="single-page main-grid-border">
		<div class="container">
			<ol class="breadcrumb" style="margin-bottom: 5px;">
				<li><a href="index.html">Home</a></li>
				<li><a href="all-classifieds.html">All Ads</a></li>
				<li class="active"><a href="mobiles.html">Mobiles</a></li>
				<li class="active">Mobile Phone</li>
			</ol>
			<div class="product-desc">
				<div class="col-md-7 product-view">
					<h2>{{ product_detail.name }}</h2>
					<p> <i class="glyphicon glyphicon-map-marker"></i><a href="#">state</a>, <a href="#">city</a>| Added at
                        {{ product_detail.created }}, Ad ID: 987654321</p>
					<div class="flexslider">
						<ul class="slides">
                            {% for image in product_images %}

                                <li data-thumb="{{ image.product_image.url }}">
                                    <img src="{{ image.product_image.url }}" />
                                </li>

                            {% endfor %}
						</ul>
					</div>
					<!-- FlexSlider -->
					  <script defer src="{% static 'js/jquery.flexslider.js' %}"></script>
					<link rel="stylesheet" href="{% static 'css/flexslider.css' %}" type="text/css" media="screen" />

						<script>
					// Can also be used with $(document).ready()
					$(window).load(function() {
					  $('.flexslider').flexslider({
						animation: "slide",
						controlNav: "thumbnails"
					  });
					});
					</script>
					<!-- //FlexSlider -->
					<div class="product-details">
						<h4>Brand : <a href="#">{{ product_detail.brand }}</a></h4>
						<h4>Views : <strong>150</strong></h4>
						<p><strong>Description: </strong>{{ product_detail.description }}</p>
					
					</div>
				</div>
				<div class="col-md-5 product-details-grid">
					<div class="item-price">
						<div class="product-price">
							<p class="p-price">Price: </p>
							<h3 class="rate">Rs. {{ product_detail.price }}</h3>
							<div class="clearfix"></div>
						</div>
						<div class="condition">
							<p class="p-price">Condition</p>
							<h4>{{ product_detail.condition }}</h4>
							<div class="clearfix"></div>
						</div>
						<div class="itemtype">
							<p class="p-price">Item Type</p>
							<h4>{{ product_detail.category }}</h4>
							<div class="clearfix"></div>
						</div>
					</div>
					<div class="interested text-center">
						<h4>Interested in this Ad?<small> Contact the Seller!</small></h4>
						<p><i class="glyphicon glyphicon-earphone"></i>00-85-9875462655</p>
					</div>
						<div class="tips">
						<h4>Safety Tips for Buyers</h4>
							<ol>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
							</ol>
						</div>
				</div>
			<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--//single-page-->

{% endblock body %}

product/templates/Product/product_list.html
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->

{% extends 'base.html' %}

{% block body %}

	<!-- Products -->
	<div class="total-ads main-grid-border">
		<div class="container">

			<div class="all-categories" style="margin-top: 20px">
				<h3> Select your category and find the perfect ad</h3>
				<ul class="all-cat-list">
                    {% for category in category_list %}
					    <li><a href="{% url 'product:product_list_category' category.slug %}">{{ category.category_name }} <span class="num-of-ads">({{ category.total_count }})</span></a></li>
					{% endfor %}
				</ul>
			</div>
			<ol class="breadcrumb" style="margin-bottom: 5px;">
			  <li><a href="/">Home</a></li>
                <li class="active"><a href="{% url 'products:product_list' %}"> All Ads </a></li>
              {% if category %}
              <li class="active">{{category}}</li>
              {% endif %}
			</ol>
			<div class="ads-grid">
				<div class="side-bar col-md-3">
					<div class="search-hotel">
					<h3 class="sear-head">Search</h3>
					<form method="GET" action="{% url 'product:product_list' %}">
						<input type="text" name="q" placeholder="Product name...">
						<input type="submit" value=" ">
					</form>
				</div>

				</div>
				<div class="ads-display col-md-9">
					<div class="wrapper">
					<div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">

					  <div id="myTabContent" class="tab-content">
						<div role="tabpanel" class="tab-pane fade in active" id="home" aria-labelledby="home-tab">
						   <div>
												<div id="container">


								<div class="clearfix"></div>
							<ul class="list">

                                {% for product in product_list %}

								<a href="{% url 'product:product_detail' product.slug %}">
									<li>
									<img src="{{ product.image.url }}" title="" alt="" />
									<section class="list-left">
									<h5 class="title">{{ product.name }}</h5>
									<span class="adprice">{{ product.price }}</span>
									<p class="catpath">Mobile Phones » {{ product.brand }}</p>
									</section>
									<section class="list-right">
									<span class="date">{{ product.created }}</span>
									<span class="cityname">City name</span>
									</section>
									<div class="clearfix"></div>
									</li>
								</a>

                                {% endfor %}

							</ul>
						</div>
							</div>
						</div>

                      {% if product_list.has_other_pages %}

                            <ul class="pagination pagination-sm">
                                {% if product_list.has_previous %}
                                    <li><a href="?page={{ product_list.previous_page_number }}">Prev</a></li>
                                {% else %}
                                    <li class="disabled"></li>
                                {% endif %}

                                {% for pages in product_list.paginator.page_range %}
                                    {% if product_list.number == pages %}
                                        <li><a href="#">{{ pages }}</a></li>
                                    {% else %}
                                        <li><a href="?page={{ pages }}">{{ pages }}</a></li>
                                    {% endif %}
                                {% endfor %}

                                {% if product_list.has_next %}
                                    <li><a href="?page={{ product_list.next_page_number }}">Next</a></li>
                                {% else %}
                                    <li class="disabled"></li>
                                {% endif %}
                            </ul>

                      {% endif %}
					  </div>
					</div>
				</div>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!-- // Products -->

{% endblock body %}